module.exports = (robot) =>
{
    const prefix = robot.config.prefix;

	let oppTopic = `__Heroic Opportunities__
Function: Generates a random Heroic Opportunity for use in Mass Battle
Form`;

	let heroicOpportunities = ["**A Clear Shot**\nThe front lines break, and you have a clear shot at the leader of the opposing army with a ranged attack! The TN of the shot depends upon the commander and his Armor TN, although given the chaotic nature of the conflict it should not be less than 30. A successful hit is worth 4 Glory, even though a killing shot is highly unlikely. If the shot is successful, the enemy general suffers a penalty of -5 to his next Battle Roll.", 
	"**Attack the Archers**\nSuddenly, your character sees a path that leads directly to the reserves of the opposing army. You have an opportunity to attack their archers, thus making an opportunity for the reinforcements to charge.If the attack against the archers (which is a skirmish) is successful, the opposing general has a penalty of -5 to his next Battle Turn, and the character conducting the attack gains 2 Glory.",  
	"**Attack the Shugenja**\n\nA break opens in the battle and you have the opportunity to attack the reserves. The enemy shugenja suddenly stop their battle rituals as you charge into their ranks! \nA successful attack on an opposing shugenja, while exceedingly dangerous, can be the key to victory. The loss of such a vital resource results in the opposing general suffering a penalty of -5 to his next Battle Roll. The attacking character gains 3 Glory. Because of the relative scarcity of shugenja, it is considered honorable to offer them a chance to surrender. Doing so gains you 2 Honor, whether they choose to accept your offer or not.",
	"**Be Prepared to Dig Two Graves**\n\nYou see a samurai from the enemys army cut down one of your kinsmen. You may spend the rest of this battle seeking that samurai.\nIf the character chooses to pursue his enemy, he must enter the enemys level of engagement and succeed at a Contested Battle/Perception Roll to locate him. If the character fails, his enemy eludes him. If he succeeds, he may immediately initiate the Show Me Your Stance opportunity. If the opponent wishes to confront the character, the GM may choose to ignore the Contested Roll.",
	"**Break the Line**\n\nYou receive the command to charge the enemys front line!\nThe character must face 2 to 4 Rank 2 samurai to successfully attack the front line. The character is immediately moved to the Heavily Engaged level. During the next Battle Turn reduce the characters roll by 2, but add 3 to his generals Battle Roll. The character gains 3 Glory.",
	"**Few against Many**\n\nYou watch as an ally charges into the midst of battle. His fate is sealed as enemies surround him, unless someone comes to his aid.\nTreat this opportunity as a skirmish against 3-6 samurai of one rank lower than the character (to a minimum of Rank 1). If the characters ally survives, the character gains 3 Glory and may be awarded the Allies Advantage at the GMs discretion.",
  "**Break the Line**\n\nYou receive the command to charge the enemys front line!\nThe character must face 2 to 4 Rank 2 samurai to successfully attack the front line. The character is immediately moved to the Heavily Engaged level. During the next Battle Turn reduce the characters roll by 2, but add 3 to his generals Battle Roll. The character gains 3 Glory.",
	"**Fire the Sails**\n\nOne certain way to attack an enemy ship is to burn its sails and render it immobile. You may accomplish this with a well-placed flaming arrow. The TN of this shot depends upon the distance between the ships. A successful shot renders the ship immobile until a new sail can be hung, and reduces the opposing general’s next Battle Roll by 3.",
  "**For the Empire**\n\nThe hideous creatures you face seem unfazed by the deaths of so many among their ranks, pressing forward despite heavy losses. Suddenly you notice a Shadowlands warrior shouting commands to the foul creatures. Perhaps the death of their leader will have more impact.\nThe samurai may fight a Lost samurai of one Rank higher than the character, a minor oni of some sort, or any other corrupted foe the GM prefers. If the battle is successful, the character gains 3 Glory. The opposing general suffers a penalty of -5 to his next Battle Roll.",
  "**Hold the Ground!**\n\nYour commander tells you to hold the line! If you and your troops can hold your ground, you will bring great glory and honor to your Clan. \nThe character and the unit he is with must hold the line against opposing forces. If they are Engaged, they must face a number of opponents equal to their number plus 2, and gain 2 Glory if successful. If Heavily Engaged, an additional +2 opponents are present, and the Glory gain is increased to 4.",
  "**Join the Battle**\n\nIn your position at the army’s reserves, you see a hole in the enemy general’s strategy. Perhaps now is the time to bring your strength into the battle! \nThe character can choose to move his position to Disengaged. If he chooses to do so, he immediately rolls again on the Battle Table with no modifiers to the roll.",
  "**Overwhelm**\n\nYou and the troops in your unit see an enemy commander in the midst of battle with no guardians, separated in the chaos of battle. Though it may not be the most honorable thing to do, overwhelming him might give your army a deciding advantage. \nThe character and any others in his unit may decide to attack a single samurai of Rank 3 or 4. If this Opportunity is successful, the opposing general suffers a -5 penalty to his next Battle Roll.",
  "**Pick up the Banner**\n\nYou see the banner carrier fall to arrows. You have the opportunity to carry the army’s banner, boosting your army’s morale. However, the banner carrier is a choice target for enemy soldiers. The character that accepts the burden of the army’s banner will be attacked by many samurai and archers every Battle Turn until he abandons the banner. During every Battle Turn the character holds the banner, his general gains a +3 bonus to his Battle Roll.",
  "**Protect the General**\n\nYou suddenly come across the army’s general, who has lost his personal guard. The general commands you to stand at his side and protect him from attack. You must follow him wherever he goes (some generals are more courageous than others). Direct this character’s level of engagement for the rest of the battle. The character gains one extra point of Glory every Battle Turn.",
  "**Rally the Archers**\n\nYour army’s archers are in disarray. You must regroup your ranged troops and ready them to fi ght once more. The PC must use inspirational words and a roll of Perform: Oratory / Awareness at a TN of 20 to succeed. If successful, his general gains +5 to his next roll, and the PC gains 1 point of Glory. If this Battle Opportunity fails or is refused, his general suffers -5 to his next roll.",
  "**Save a Wounded Comrade**\n\nIn the midst of battle, you notice a kinsman has fallen! You have the opportunity to save him. \nWhile saving his comrade, the character cannot undergo any other Heroic Opportunities. Each Battle Turn, the character faces two or three Rank 1 or 2 opponents. If the character successfully defends the fallen comrade, he gains an additional point of Glory for each Battle Turn (and the ally may wish to bestow gifts in return for his life).",
  "**Save a Wounded Opponent**\n\nBetween breaths you notice a wounded enemy. He calls out for you to help him. You may ignore him without penalty (he is acting cowardly, after all), but if you aid him, he will be morally obliged to you. The opponent could also become a valuable hostage to be used in negotiations with the enemy- The character must move to the Reserves level of activity as soon as he can. The character gains no bonuses for completing this Opportunity.",
  "**Save our Ship**\n\nYour ship has been the target of heavy fire throughout the entire battle, and you fi nd out it has suffered structural damage. In a few moments it will sink, and without warning your crewmates will all die. You must warn the others and help them off the ship. If the character successfully saves the lives of his crewmates, he gains 3 Glory.",
  "**Shadowlands Madness**\n\nThe curse of the Shadowlands Taint falls upon those fighting by your side and they fall to the ground, screaming. A few moments later they rise again - with an unholy gleam in their eyes. \nThe character must fight against 1 to 4 Tainted samurai either equal to the PC’s Rank (in Heavily Engaged) or one lower (in Engaged). The character gains 1 Glory for succeeding. If the character fails this Opportunity, his general has a -3 penalty to his next Battle Roll..",
  "**Show me your Stance**\n\nAn enemy commander notices you and loudly challenges you to a duel. \nIf the character accepts, initiate a duel against a samurai of Rank 2 or 3. If the character wins, he gains one point of Glory for each Glory Rank of his opponent; additionally, his general gains a +2 bonus to his next Battle Roll.",
  "**Shugenja's Gift**\n\nOne of the shugenja of your army has targeted you with a spell. The GM may decide what spell it is; alternatively, just consider one of the character’s Traits or Skills to be one Rank higher until the end of the battle.",
  "**Skirmish**\n\nThis Opportunity gives a character the opportunity to fight a number of enemies determined by the GM. A character needs only to force his enemies out of the fi ght to succeed at this Opportunity; he does not need to kill them. If the character is successful in this Opportunity, add +1 to his general’s next Battle Roll.",
  "**Stand against the Darkness**\n\nThe ashigaru troops and some craven samurai in your army are unused to fi hting undead abominations and the stuff of nightmares. They break and run at the sight of a huge Oni slowly marching on their position. If you can defeat the beast, perhaps your example will raise the morale of your army. \nThe character may fight a minor oni or other similar opponent. If he succeeds, the character gains 4 Glory and his general gains a +3 bonus to his next Battle Roll. If he fails, or if this Opportunity is refused, the general suffers -5 to his next Battle Roll.",
  "**Take the Enemy Banner**\n\nBetween the blood and carnage you spot the standard bearer of the opposing army. You have the opportunity to take the enemy’s banner! You must kill the bearer in combat to take it. If you take it, you must try to get it back to your Reserves. \nWithout the help of the character’s army, this Opportunity is nigh impossible to complete. While the character holds the enemy banner, he cannot undergo any other Heroic Opportunity. Each Battle Turn, the character is assaulted by a number of enemy samurai (chosen by the GM) of equal Rank. On each Battle Turn the enemy banner is in the character’s possession, impose a -5 penalty to the enemy general’s Battle Roll. When this Opportunity is completed, the character gains a Rank of Glory.",];

	robot.registerHelpTopic( /Opportunity/i, oppTopic );
	robot.registerCommand( /Opportunity/i, `\`${prefix}Opportunity\`: __Heroic Opportunity__ Select a random Heroic Opportunity in Mass Battle.`, ( message, test ) =>
	{
		message.channel.send( heroicOpportunities[Math.floor(Math.random() * heroicOpportunities.length)])
	});
}


/*var rdm = messages[Math.floor(Math.random() * messages.length)];



return rdm;*/