module.exports = (robot) =>
{
	robot.registerBattle( "mass battle", "The Mass Battle system allows characters to determine how involved in the fi ghting they are, and then uses the characters� capabilities to determine how well they are faring at that level. Conflicts of this scale are measured in Battle Turns, which consist of thirty minutes each. Every character participating in the battle must determine the results of their involvement once per Battle Turn. The length of a battle can vary wildly, but a good rule of thumb is that one Battle Turn takes place per 250 troops on each side. So a battle between two forces of 500 men each would take two Battle Turns to resolve. Each Battle Turn takes place in stages.");
	robot.registerBattle( "mass battle stage 1", "`Stage 1: Declaration` \nDuring the Declaration Stage, all characters participating in the battle should determine their level of involvement. These range from Reserves, where a character is positioned well behind the front lines and relatively safe from the vast majority of his enemies, to Heavily Engaged, in which the character is positioned on the very front lines and as such is situated right in the middle of his foes. Each character may choose to be in one of the following four levels: Reserves, Disengaged, Engaged, or Heavily Engaged. \n\nOnce a characters level of involvement has been determined, the GM should make a Contested Battle (Mass Combat) / Perception Roll between the generals in command of the rival armies. If one of the generals wins the roll by 5 or more, that generals army is considered to be winning while the other side is losing. If the difference is less than 5, the battle is considered even. GMs may modify the results of this roll based on numerical advantage, terrain, weather conditions, successful Heroic Opportunities in previous Battle Turns, or any of a litany of other factors as they see fit.");		robot.registerBattle( "mass battle stage 2", "`Stage 2: Determination` \nWith the characters� involvement and the current status of the battle determined, each player rolls one die and adds to it his character�s Water Ring and his Battle Skill, if any. The total of this roll is compared to the Battle Table to determine how much Glory the character has accumulated, how many Wounds he has suffered, and whether or not he encounters a Duel or Heroic Opportunity. If he does encounter a Duel or Heroic Opportunity, the character proceeds to Resolution (below). If a character does not encounter a Duel or Heroic Opportunity, then after he rolls to see how much Glory and/or Wounds he has accrued, the Battle Turn ends for him.");
	robot.registerBattle( "mass battle stage 3", "`Stage 3: Resolution` \nCharacters who encounter a Duel or Heroic Opportunity have a special opportunity to take a more dramatic role in the battle. A result of Duel on the Battle Table indicates the character has come across an opponent of roughly equivalent skill, and the two have engaged in a private duel. Such events are generally allowed to play out by other samurai on the battlefield, because interfering suggests the samurai being aided is incapable of dealing with the matter, a grievous insult. These duels may be traditional iaijutsu duels, or they can simply be one-on-one skirmishes with whichever weapons are available, depending upon the combatants.");
	robot.registerBattle( "heroic opportunities", "`Heroic Opportunities` are somewhat more elaborate skirmish situations that arise depending upon where a character is situated in the battle. They generally involve an opportunity for greater glory on the battlefi eld, although they can easily lead to a characters death if he oversteps his abilities. A character does not have to accept a Heroic Opportunity - he can decline, taking the better part of valor, although this will often have a negative impact on the course of the battle.");
	robot.registerBattle( "battle table", "https://cdn.discordapp.com/attachments/1067148233861779506/1071658337936097280/image.png");
	//-robot.registerBattle( "opportunity random", randomMessage());

	//robot.registerBattle( "", "");
}

