module.exports = (robot) =>
{
	robot.registerGuide( "void points", "Gain a bonus of +1k1 to one Skill, Trait, Ring, or Spell Casting Roll\nTo increase a Skill from 0 to 1 for the Round.\nReduce Wounds suffered by 10. \nIncrease Armor TN by 10 for one Round.\nSwitch Initiative with one willing target for the rest of the skirmish.\nIncrease his Initiative Score by 10 for the rest of the skirmish.\nIncrease the Damage of a Katana by +1k1");

	robot.registerGuide( "stances", "insert rules for stances here");
		robot.registerGuide( "full attack", "Cannot take any Simple or Complex action other than to attack, and can only move towards his enemies. Cannot be used to deliver ranged attacks. Attacks gain a +2k1 bonus that round but Armor TN is reduced by 10. Move actions increase the traveled distance by extra 5 feet. Cannot be used while mounted.");
		robot.registerGuide( "attack", "Standard stance. No bonus and no penalties.");
		robot.registerGuide( "center", "No action is taken this round. On the next round, the samurai gains a +1k1 plus his Void Ring bonus to one roll. The samurai also adds 10 to his Initiative for that round only.");
		robot.registerGuide( "defense", "Add the Air Ring plus Defense Skill rank to Armor TN while in this stance. Cannot attack directly but can cast spells (even attack spells).");
		robot.registerGuide( "full defense", "Roll Defense / Reflexes and add half to Armor TN. Counts as a Complex action for the round.");

	robot.registerGuide( "maneuvers", "These are some specialized actions that you may do but require raises");
		robot.registerGuide( "called shot", "Requires Raises to strike specific body parts (1 for a limb, 2 for a hand/foot. 3 for the head, 4 for a small part (eye, ear, etc.))\n\tpage 176 of **Book of Air** has optional called shots for archery.");
		robot.registerGuide( "disarm", "Inflicts 2k1 damage and forces a Contested Strength Roll. If the target loses, he drops the weapon. This requires 3 Raises.");
   robot.registerGuide( "huge", "A Huge creatures can not be targeted by Grapples or the Knockdown maneuver and will not start a grapple unless it has ranks in Juijutsu.");
   robot.registerGuide( "invulnerability", "A creature with invulneralility takes normal damage from magic, Nemurani or weapons made jade, crystal, obsidian, or crysteel. Any other sources of damage will only deal 1 damage.");
   robot.registerGuide( "invulnerability partial", "A creature with invulneralility partial is only invulnerable against certain types of damage like fire, or arrow. Attacks from these sources only deal 1 damage. The creature will still take normal damage from magic, Nemurani or weapons made jade, crystal, obsidian, or crysteel.");
   robot.registerGuide( "jade powder", "ground up jade dust mixed with a sticky paste to adhere to weapons. this apply the jade tag to the weapons for 3 round. However its stopgap measure with the powder losing effectiveness. the first hit the powder is applied you deal full damage. The second round is half damage. the third round is one quarter damage. After 3 hits the powder is exausted. \nApplying jade powder to a weapon is considered a complex action.");
   robot.registerGuide( "invulnerability superior", "A creature with invulneralility that would normally take regular damage from magic, Nemurani or weapons made jade, crystal, obsidian, or crysteel is now invulnerable to one or more of those sources IE jade or Air spell. Any other sources of damage will only deal 1 damage.");
   robot.registerGuide( "spirit", "Creatures with this tag only take half damage from normal weapons and attacks that are do not contain jade, crystal, obsidian, or crysteel. Any spell or magical effect that contains the tag jade, crystal, obsidian may deal normal damage.");
   robot.registerGuide( "swift", "Creatures with switch are considered to have water rings of one rank higher for the purposes of calculating how far they can move with free and simple move actions. This does not increase their max move value as stated by their water ring.");
   robot.registerGuide( "undead", "The dead are immune to fear effect as well as any spell, skill, or technique that tempts to influnce their mind or emotions.");
		robot.registerGuide( "extra attack", "By making 5 Raises on an attack roll, the character may immediately make a second attack roll after the first attack resolves.");
		robot.registerGuide( "feint", "Requires 2 Raises on an attack roll. If successful, half the amount by which the attack exceeded the target's Armor TN is added to the damage roll (max of attacker's Insight Rank x5).");
   robot.registerGuide( "glory table", "https://cdn.discordapp.com/attachments/1216471349552480298/1274131888738402435/image.png?ex=66c1234a&is=66bfd1ca&hm=7ccb86ddfbce687d9b43b1f92bc6f28c53e82e1dff2aa76522ae78c07fc3ee4f&");
   robot.registerGuide( "honor table", "https://cdn.discordapp.com/attachments/1216471827400888571/1274233127128006780/image.png?ex=66c18193&is=66c03013&hm=b45c1339b4d7bc98a5d8e909014feccdf679f15eef48e131548ad420d6bbd74a&");
		robot.registerGuide( "guard", "A Simple Action that cannot be taken in the Full Attack Stance. When using Guard, choose one person within 5' of you. and their Armor TN is increased by 10. Your Armor TN is decreased by 5 while using Guard.");
   	robot.registerGuide( "falling", "Falls of greater then 10 feet deal 1k1 in wounds plus an additional 1k1 for ever 10 feet beyond that");
    robot.registerGuide( "ambush", "If the gm rules that one group is unaware of the other presence the hidden group may attempt a surpise attack. They make a conestested roll of Stealth (Ambush) / Agility vs Investigation (notice) / Perception before the first stage of combat.\nAmbushes may us the Cumulative Sill roll or if the GM prefers just have the leaders of either groups make the roll.\nIf the ambusing party wins the contested roll then the surprised party suffers a -10 to their initiative rolls.");
   	robot.registerGuide( "drowning", "A character that falls into deep water must roll Athletics (Swimming) / Strength vs TN15 each minute to stay afloat. This TN may be increased based on other factors like a storm tossed sea. \nIf the player must tread water for an extended peroid of time the TN will increase and the roll will adjust to Athletics (Swimming) / Stamina.\nOnce the player fails the roll he can hold their breath for a number of rounds equal to their stamina during which time they can make an athletics roll to resume swimming.\nIf the player is still under water when their Stamina runs out they will start to drown. suffering 2k2 wounds per round, the player is helpless and cannot take any actions until rescued."); 
		robot.registerGuide( "increased damage", "For every Raise made on an attack roll, you gain a bonus of + 1K0 to the damage roll for that attack.");
		robot.registerGuide( "knockdown", "Requires 2 or 4 Raises (for 2 or 4 legged opponents) on an attack roll. If successful, the attack deals normal damage, This will also trigger a contested Strength roll if the one being struck loses then target is rendered Prone (see Conditions).");
		robot.registerGuide( "interrupted", "When you are attacked while casting a spell make a Willpower Roll vs TN 5 + Wounds suffered (TN 10 if the attack missed)");
		
	//robot.registerGuide( "", "");

}