module.exports = (robot) =>
{

        robot.registerGuide( "crafting", "`Crafting` here are the core rules for crafting. Crafting requires both time and materials, since samurai are above such dishonorable concerns as money, it is assumed that materials are provided to you.\n `Unit of time based on Material`\n              Steel		Metal/Glass		Other\nZeni      	-	          	Days	         	Hours\nBu      	Days	      	Days	          	Days\nKoku	Weeks		    Days	              Days\n\n`Time Units Based on Price`\n`Zeni` - Price Divided by 10 (minimum 1)\n`Bu` - Price Divided by 5 (minimum 1)\n`Koku` - Price Divided by 3 (minimum 1)\n\n `Difficulty Crafting`\n                             Zeni          		Bu	            	Koku \nCost 1-10     	TN10	          	TN15	         	TN20 \nCost  11-25      TN15	         	TN20	         	TN25 \nCost  26-50	TN20		         TN25	             TN30 (Koku cost 21-25) \nCost 50+      	TN25+	          TN30+        	   TN 35 (Koku Cost 25+)\n\n for each increment of 5 add 5 to the TN");		
   
   robot.registerGuide( "crafting sacred weapon", "A smith of a clan that possesses a Sacred Weapon (as per the Advantages in the L5R 4th Edition Core Rulebook, page 152-153) may attempt to make one using a Craft: Weaponsmithing roll. The smith must create the appropriate Excellent Quality weapon with 7 Raises (6 Raises for a Kaiu smith).\n\nA samurai may only attempt to create a Sacred Weapon of his own clan. A Crane can only attempt to make Kakita Blades, a Crab may only attempt to make Kaiu Blades, and so forth.");

robot.registerGuide( "crafting excellent weapon", "To create an `Excellent` weapon, the regular Crafting rules are used. However, the cost of materials and the koku value of the weapon are both tripled.A smith must have a Craft: Weaponsmithing Skill Rank of at least 7 to create an Excellent weapon. A Kaiu or Tsi smith may create an Excellent weapon with a Skill Rank of at least 5.\n \nA smith who creates an Excellent weapon may call Raises to confer one Special Quality on the weapon. Players and GMs are encouraged to come up with their own properties. However, failure on the Crafting roll means the weapon is wholly ruined and useless; the smith must try again. A list of Qualities and the associated Raises is provided below. Characters trained in the Tsi or Kaiu schools receive one Free Raise for the purpose of conferring Special Qualities. \n\n`Balanced:` The wielder gains +1k0 on attack rolls using this weapon. __Raises: 4__ \n`Radiant:` This weapon counts as Jade for the purpose of attacking Invulnerable targets. __Raises: 6__ \n`Signature:` This weapon bears a unique signature stamp, identifying it with its creator. __Raises: 2__ \n`Swift:` The wielder gains +5 to his Initiative score while using this weapon. __Raises: 4__ \n`True:` This weapon decreases the targets Reduction by the wielders Strength. __Raises: 6__ \n`Unbreakable:` This weapon cannot be broken. __Raises: 5__");

	robot.registerGuide( "casting", "`Casting` How to Cast a Spell \nYou roll the ring of the spell + school rank keeping the ring vs 5 + (mastery level of the spell * 5) as the TN");
 
		robot.registerGuide( "importune", "`Importune` is used to talk to the kami \n Importune Emphasis is used in a manner of a Social Skill when using the Commune spell to converse with a spirit, and especially when trying to persuade that spirit to be helpful \n Spellcraft (importune) / Intelligence  vs 15 + (mastery level of the spell * 5) as the TN");
   
		robot.registerGuide( "spell research", "`Spell Research`  allows you to formulate new spells.\nSpellcraft (Spell Research) / Intelligence vs 10 + (Spell's Mastery Level * 10) as the TN. This requires a number of weeks of uninterrupted study equal to the new spell's Mastery Level.");
   
   		robot.registerGuide( "honor", "`Discerning Honor` Find out how honorable another character is \nA samurai can find out the Honor rank of another by making a Lore: Bushido / Awareness vs (TN 30)");
      
     	robot.registerGuide( "recognize", "`Recognize` Find out how to recognize another character \nTo recognize another character make a Lore: Heraldry / Intelligence vs TN 50-(5 * the target's glory rank)");
      
    	robot.registerGuide( "commercial warfare", "`Commercial Warfare` This is an Optional rule to expand the concept \nAny time two (or more) merchants are clashing in a particular market, the GM can call for  Contested Rolls of Commerce (Merchant) / Awareness, with the winning merchant inflicting a koku loss equal to the difference between the rolls on the losing rival. If multiple merchants are rolling against each other, the GM may add more options, such as allowing the winner to divide the losses between the losers, or letting the middle roll inflict a halved loss on those below.\nIf this option for commercial warfare is used, the Daidoji Trading Council technique should be changed to award a +2k1 bonus to any Commerce rolls made when performing commercial warfare.");
      
robot.registerGuide( "actions", "`Actions` This will describe the action economy \nA Character may take of the two following options \n\n`*` One Complex Action + free actions \n`*` Two Simple Actions + free action \n\n`Free action:` Draw a Weapon (small) \n`Free action:` Speak up to 5 words \n`Free action:` Move action (water * 5ft) \n`Free action:` Pull out a spell scroll \n`Free action:` Drop a weapon or item \n\n`Simple Action:` Activate a kata \n`Simple Action:` Draw a weapons (medium or large) \n`Simple Action:` Move action (water * 10ft) \n`Simple Action:` Dismount a horse \n`Simple Action:` Guard someone \n`Simple Action:` Pick up a weapon or item \n`Simple Action:` Put away a spell scroll \n`Simple Action:` Speak more than 5 words \n`Simple Action:` Stand up from prone \n\n`Complex Actions:` Make an attack (melee or ranged) \n`Complex Actions:` Cast a Spell \n`Complex Actions:` Use a non-weapons skill \n`Complex Actions:` String a bow for use \n`Complex Actions:` Mount a horse");

   
	//robot.registerGuide( "", "");

}