module.exports = (robot) =>
{
	robot.registerGuide( "iaijutsu", "a detailed walk through on how to conduct an iajutsu duel. \nAugment the iaijutsu command with; start, assessment, focus, strike.");
		robot.registerGuide( "iaijutsu start", "An Iaijutsu duel takes place over three Combat Rounds (Assessment, Focus, and Strike). \n `Initiative:` Both Duelists roll their initiative and then assume the Center Stance on the initiative of the faster Duelist. The Center Stance bonus (1k1+Void) will be available on both Round Two (for the Focus roll) and on Round Three for either the Strike roll or a damage roll, as the player chooses.\nmove to assessment");
		robot.registerGuide( "iaijutsu assessment", "`Round One` - Assessment \nIaijutsu (Assessment) / Awareness roll against a TN of 10 plus their opponent’s Insight Rank x 5. If successful, the samurai learns one of these facts, plus one more per each Raise \n`•`Opponent’s: Void \n`•`Opponent’s: Reflexes \n`•`Opponent’s: Iaijutsu Skill \n`•`Opponent’s: Iaijutsu emphases \n`•`Opponent’s: current Void points available \n`•`Opponent’s: current Wound level \nIf either beats the other’s roll by 10 or more, he gets +1k1 bonus on the Focus roll.\nmove to focus");
		robot.registerGuide( "iaijutsu focus", "`Round Two` - Focus \nBoth make a contested Iaijutsu (Focus) / Void roll. If one beats the other by 5 or more, he has earned the right of first strike. A Free Raise is earned for every additional 5 points the other is beaten. If neither beats the other by at least 5, both strike at the same time.\nmove to strike");
		robot.registerGuide( "iaijutsu strike", "`Round Three` - Strike \nAttack normally with Iaijutsu / Reflexes, using any Free Raise earned on the previous stage. The second samurai may then strike after the first. If the duel was to the first blood, the second samurai has lost. If the duel was to the death, the duel becomes a standard skirmish until either one is dead. The act of striking counts as each character’s action for this round.");
	
	robot.registerGuide( "taryu-jiai", "a detailed walk through on how to conduct a Taryu-Jiai this is a duel between shugenja using the kami as proxy. \nAugment the Taryu-Jiai command with; start, assessment, empower, strike, optional.");
		robot.registerGuide( "taryu-jiai start", "A Taryu-Jiai duel takes place over three Combat Rounds (Assessment, Empower, and Strike). p184 Book of Fire \n `Initiative:` Both Shugenja roll their initiative and then assume the Attack Stance on the initiative of the faster Shugenja. Then Select which element they wish to use during the duel excluding Void there are no Void duels. \nmove to assessment");
		robot.registerGuide( "taryu-jiai assessment", "``Round One` - Assessment \nEach Shugenja rolls a contested Spellcraft / Void vs their opponent the Shugenja who wins learns the ring his opponent has selected along with their rank in that ring. If winner succeeds by more than 10 he may also learn their school rank or Void rank. \nEither Shugenja may acknoeledge defeat and end the duel.\nif neither concedes move to empower.");
		robot.registerGuide( "taryu-jiai empower", "`Round Two` - Empower \This stage of the duel is considered to be full concentration, meaning the shugenja may only perform Free Actions and can potentially be disrupted by outside distractions. This will also often produce very impressive visual effects as the kami gather and swirl around the two shugenja, as well as glowing eyes with the power of the kami affecting everything. `Taryu-Jiai optional` maybe used in this round. \nMove to strike");
		robot.registerGuide( "taryu-jiai strike", "`Round Three` - Strike \n Each Shugenja rolls a contested Spellcasting roll using the element of their choice, any affinity or deficiency apply as normal. Spell slots of that element are used as well. School Techniques normally do not apply but a gm may allow them. \n The shugenja who wins the contested Spellcasting roll will damage his opponent by 2k2 + with an additional 1k1 for every 5 points he beats his opponent’s roll. \nThe shugenja who lost inflicted half as many dice rounded down as the winner. \n if not-lethal the shugenja who inflicts more wounds wins \n if lethal, repeat Empower and Strike till one shugenja falls. \n If the duel is lethal and a shugenja is reduced to down or out the opponent's kami overwhelms them and is slain.");
		robot.registerGuide( "taryu-jiai optional", "`Taryu-Jiai optional` is optional rule a gm may allow during a duel \n`Disruption` During the empower phase of the duel a shugenja may try to disrupt their opponents casting by making a contested Spellcaft / Element roll (where the element is what each duelist chose at the start of the duel). \nIf one duelist beats the other’s roll by greater then 10 then the winner receives +1k1 damage bonus on the strike roll");
	
	robot.registerGuide( "sumo", "`Sumo` How to conduct a Sumai Tournament if you wish not to use the grappling rules. \nTo represent sumai tournament wrestling, simply have the two wrestlers perform a Contested Roll of Jiujutsu (Sumai) / Strength. If one wrestler wins the Contested Roll by 5 or more, he wins the match (either knocking his opponent down or forcing him out of the ring). If neither wrestler beats the other’s roll by at least 5, the bout continues and another Contested Roll is made. \nSumo gain a considerable advantage from being larger and heavier than their opponents. GMs may represent this by awarding a +1k0 bonus to the roll for the larger wrestler, e.g. for a Large wrestler facing a normal or Small wrestler, or a normal wrestler facing a Small one. \nGMs who want to add a little more depth to their sumai tournaments may also wish to incorporate the stare-down that takes place before each match, when each sumo seeks to intimidate the other and gain a psychological advantage. This can be represented with a Contested Roll of Intimidation / Willpower, with a wrestler who wins the roll by 5 or more gaining a +1k0 bonus to the subsequent Jiujutsu roll");
 
 	robot.registerGuide( "grappling", "`Grappling` a unique combat situation that may occur during a skirmish\nA samurai initiates a grapple with a Jiujutsu / Agility roll versus Armor TN. If successful, target is grappled until his turn, when he can attempt to control the grapple. Gaining control is a contested Jiujutsu / Strength roll. Winner has control until the other’s turn.\nController may do the following\n`Hit:` Deal unarmed (Strength k1) damage as a Complex action. Throw: Target is thrown and becomes prone within 5 feet. Target is no longer in the grapple. Complex action.\n`Break:` Ends the grapple as a Simple action. \n`Pass:` As a Free Action, the character may do nothing, choosing to maintain the grapple and retain control");
  
   	robot.registerGuide( "new user", "`New User`, Hello and welcome to Rokugan here are some resources to help you get started. \n`New Player Guide` - https://docs.google.com/document/d/1OFCqO9miT47h1jqs41bhxl7zsQRNp7-saMyBPNiKSKA/edit?usp=sharing \n`Guide to Factions` - https://docs.google.com/document/d/1RzpO_KdyGuPOQxVjAZwTCM24qzDz5uWaS57qzIrJHrU/edit#heading=h.62kyerl65d99 \n`Guide to Monks` - https://docs.google.com/document/d/1NiIsR5kdNBE6QSRe_Ga5u-7glbNr_X8vSz3hfctrsdM/edit?usp=sharing");
	
	//robot.registerGuide( "", "");

}