module.exports = (robot) =>
{
	robot.registerGuide( "iaijutsu", "a detailed walk through on how to conduct an iajutsu duel. \nAugment the iaijutsu command with; start, assessment, focus, strike.");
		robot.registerGuide( "iaijutsu start", "An Iaijutsu duel takes place over three Combat Rounds (Assessment, Focus, and Strike). \n `Initiative:` Both Duelists roll their initiative and then assume the Center Stance on the initiative of the faster Duelist. The Center Stance bonus (1k1+Void) will be available on both Round Two (for the Focus roll) and on Round Three for either the Strike roll or a damage roll, as the player chooses.\nmove to assessment");
		robot.registerGuide( "iaijutsu assessment", "`Round One` - Assessment \nIaijutsu (Assessment) / Awareness roll against a TN of 10 plus their opponent’s Insight Rank x 5. If successful, the samurai learns one of these facts, plus one more per each Raise \n`•`Opponent’s: Void \n`•`Opponent’s: Reflexes \n`•`Opponent’s: Iaijutsu Skill \n`•`Opponent’s: Iaijutsu emphases \n`•`Opponent’s: current Void points available \n`•`Opponent’s: current Wound level \nIf either beats the other’s roll by 10 or more, he gets +1k1 bonus on the Focus roll.\nmove to focus");
		robot.registerGuide( "iaijutsu focus", "`Round Two` - Focus \nBoth make a contested Iaijutsu (Focus) / Void roll. If one beats the other by 5 or more, he has earned the right of first strike. A Free Raise is earned for every additional 5 points the other is beaten. If neither beats the other by at least 5, both strike at the same time.\nmove to strike");
		robot.registerGuide( "iaijutsu strike", "`Round Three` - Strike \nAttack normally with Iaijutsu / Reflexes, using any Free Raise earned on the previous stage. The second samurai may then strike after the first. If the duel was to the first blood, the second samurai has lost. If the duel was to the death, the duel becomes a standard skirmish until either one is dead. The act of striking counts as each character’s action for this round.");
	
	robot.registerGuide( "taryu-jiai", "a detailed walk through on how to conduct a Taryu-Jiai this is a duel between shugenja using the kami as proxy. \nAugment the Taryu-Jiai command with; start, assessment, empower, strike, optional.");
		robot.registerGuide( "taryu-jiai start", "A Taryu-Jiai duel takes place over three Combat Rounds (Assessment, Empower, and Strike). p184 Book of Fire \n `Initiative:` Both Shugenja roll their initiative and then assume the Attack Stance on the initiative of the faster Shugenja. Then Select which element they wish to use during the duel excluding Void there are no Void duels. \nmove to assessment");
		robot.registerGuide( "taryu-jiai assessment", "``Round One` - Assessment \nEach Shugenja rolls a contested Spellcraft / Void vs their opponent the Shugenja who wins learns the ring his opponent has selected along with their rank in that ring. If winner succeeds by more than 10 he may also learn their school rank or Void rank. \nEither Shugenja may acknoeledge defeat and end the duel.\nif neither concedes move to empower.");
		robot.registerGuide( "taryu-jiai empower", "`Round Two` - Empower \This stage of the duel is considered to be full concentration, meaning the shugenja may only perform Free Actions and can potentially be disrupted by outside distractions. This will also often produce very impressive visual effects as the kami gather and swirl around the two shugenja, as well as glowing eyes with the power of the kami affecting everything. `Taryu-Jiai optional` maybe used in this round. \nMove to strike");
		robot.registerGuide( "taryu-jiai strike", "`Round Three` - Strike \n Each Shugenja rolls a contested Spellcasting roll using the element of their choice, any affinity or deficiency apply as normal. Spell slots of that element are used as well. School Techniques normally do not apply but a gm may allow them. \n The shugenja who wins the contested Spellcasting roll will damage his opponent by 2k2 + with an additional 1k1 for every 5 points he beats his opponent’s roll. \nThe shugenja who lost inflicted half as many dice rounded down as the winner. \n if not-lethal the shugenja who inflicts more wounds wins \n if lethal, repeat Empower and Strike till one shugenja falls. \n If the duel is lethal and a shugenja is reduced to down or out the opponent's kami overwhelms them and is slain.");
		robot.registerGuide( "taryu-jiai optional", "`Taryu-Jiai optional` is optional rule a gm may allow during a duel \n`Disruption` During the empower phase of the duel a shugenja may try to disrupt their opponents casting by making a contested Spellcaft / Element roll (where the element is what each duelist chose at the start of the duel). \nIf one duelist beats the other’s roll by greater then 10 then the winner receives +1k1 damage bonus on the strike roll");
   robot.registerGuide( "rumor", "`Rumors` You will have to use the Courtier skill to obtain or spread rumors about someone, using the Gossip Emphasis. This can be more difficult depending upon the targets Glory, with a suggested TN of 10 plus the target’s Glory x 5 minus your Glory x 5. GMs can have players Raise on the roll to conceal that they are the source of the gossip, and it should be noted that attempting to spread malicious rumors about someone with higher Status is generally unwise and can easily lead to a death sentence in Rokugan.");
   robot.registerGuide( "divination", "`Divination` You may attempt to use the divination skill once per day. The TN for this Skill Roll is 15, although depending upon the circumstances the GM may dictate a higher TN. If the roll is failed, a second roll may be attempted immediately if you expend a Void Point. (As usual, the TN for the second roll is increased by +10.) The results of divination attempts are notoriously vague but should give some indistinct inkling of what is to come in the immediate future (i.e. you see difficult times ahead. an old enemy returns soon a shadow will fall over your father’s house, etc).");
   robot.registerGuide( "disguise", "`Disguise` One must use the Acting skill again a TN to disguise yourself normally its tn15. This assumes that you are taking on the role of a non-specific individual who shares the same Clan affiliation, gender, and profession (bushi, courtier, or shugenja). Each of these basic features that are changed increases the total TN of the Skill Roll by +5 (for example, a male Scorpion bushi attempting to impersonate a female Crane courtier would have a base TN of 30). Attempting to imitate a specific individual is significantly more difficult, and increases the TN by a total of +15 in addition to any other increases of Clan or gender or profession. You may also Raise on your roll to make your disguise harder to see through. A character who is trying to see through your disguise must roll Investigation / Perception against a TN of 15, +5 for each Raise you made.");
   robot.registerGuide( "cipher", "`Cipher` If you possess the Cipher Emphasis for Calligraphy, you are assumed to know one cipher commonly used by your Clan. Ciphers can be very difficult to break, with varying TNs depending upon their commonality of use and means of creation. Typically, the TN to break a cipher is the result of the Calligraphy (Cipher) / Intelligence roll used to create it.");		
   robot.registerGuide( "bureaucracy", "`Bureaucracy`  The Bureaucracy Emphasis for etiquette is used when trying to maneuver through governmental channels appropriately, such as trying to arrange a meeting with someone of high Status (the Imperial bureaucracy is notoriously difficult to navigate)");
   robot.registerGuide( "interrogation", "`Interrogation`  Emphasis for the Investigation skill can be used to try to figure out if someone is lying, typically in a Contested Roll against the target’s Sincerity.");
   robot.registerGuide( "investigation", "`Investigation`  represents your ability to assess your surroundings and gather information based on physical clues. It can also represent an ability to gather information from others over a longer period of time hours or even days in order to piece together different bits of information into a cohesive picture. Unlike other Intelligence or Perception Skill Rolls Investigation can be re-rolled if you fail the initial roll. The second rall may not be made for at least an hour, however, and suffers a +15 increase to TN.");
   robot.registerGuide( "notice", "`Notice`  Emphasis for the Investigation skill is most frequently used to locate something (or someone) hidden or concealed. If this is a person in hiding, a Contested Roll will be used, pitting the character’s Investigation (Notice or Search Emphasis according to the circumstances) against the target’s Stealth.");
   robot.registerGuide( "search", "`Search`  Emphasis for the Investigation skill is most frequently used to locate something (or someone) hidden or concealed. If this is a person in hiding, a Contested Roll will be used, pitting the character’s Investigation (Notice or Search Emphasis according to the circumstances) against the target’s Stealth.");
   robot.registerGuide( "meditation", "`Meditation` with help from the Void Recovery Emphasis is the simplest means other than resting that you can recover spent Void Points. A Meditation (Void Recovery) / Void roll versus TN 20 allows you to recover one Void point with a half hour of uninterrupted meditation.");
   robot.registerGuide( "gossip", "`Gossip`  Emphasis for the Courtier skill  can also be used to obtain or spread rumors about someone using the Gossip Emphasis. This can be more difficult depending upon the targets Glory, with a suggested TN of 10 plus the targets Glory x 5, minus your Glory x 5. GMs can have players Raise on the roll to conceal that they are the source of the gossip and it should be noted that attempting to spread malicious rumors about someone with higher Status is generally unwise and can easily lead to a death sentence in Rokugan.");
   robot.registerGuide( "honesty", "`Honesty` Emphasis is used when you must speak the truth in a convincing manner. Rolls made with Sincerity can be opposed with Investigation by those who doubt the truth of the speaker’s words.");
   robot.registerGuide( "deceit", "`Deceit` Emphasis is used when you must tell a lie and appear to tell the truth. Rolls made with Sincerity can be opposed with Investigation by those who doubt the truth of the speaker’s words.");
   robot.registerGuide( "sincerity", "`Sincerity` Rolls made with Sincerity can be opposed with Investigation by those who doubt the truth of the speaker’s words.");
   robot.registerGuide( "tea ceremony", "`Tea Ceremony` to conduct a ceremony you must roll Tea Ceremony / Void roll (TN 15 + 5 for each participant after the second). The ceremony is intended for two people, but you may conduct it alone if desired, or up to five people total may be included. If the Skill Roll is successful, all participants regain a spent Void Point. The ceremony takes thirty minutes to complete successfully, and requires a quiet location to be conducted.");
   robot.registerGuide( "horse control", "Controlling a Horse is not an easy task and requires the skill horsemenship to make the horse do as you wish. \n`Controlling a Horse` to full gallop: TN10 \n`Controlling a Horse` in the presence of violence, fire, or predators: TN20 \n`Riding a Horse` into battle: TN25(made once at the start of battle)");
   robot.registerGuide( "survival", "The Survival Emphasis allows you to forage for sustenance and shelter in the wilderness, with a TN varying upon the severity of the conditions (the forest is simpler than the mountains, which are simpler than the desert, etc.)");
   robot.registerGuide( "trailblazing", "Trailblazing allows you to forge a trail through the wilderness that others can follow, making better time and requiring less work in order to follow.");
   robot.registerGuide( "tracking", "The Tracking Emphasis allows you to locate and follow the tracks of prey through rural environments, although repeated Skill Rolls are necessary for longer trails.)");
	robot.registerGuide( "sumo", "`Sumo` How to conduct a Sumai Tournament if you wish not to use the grappling rules. \nTo represent sumai tournament wrestling, simply have the two wrestlers perform a Contested Roll of Jiujutsu (Sumai) / Strength. If one wrestler wins the Contested Roll by 5 or more, he wins the match (either knocking his opponent down or forcing him out of the ring). If neither wrestler beats the other’s roll by at least 5, the bout continues and another Contested Roll is made. \nSumo gain a considerable advantage from being larger and heavier than their opponents. GMs may represent this by awarding a +1k0 bonus to the roll for the larger wrestler, e.g. for a Large wrestler facing a normal or Small wrestler, or a normal wrestler facing a Small one. \nGMs who want to add a little more depth to their sumai tournaments may also wish to incorporate the stare-down that takes place before each match, when each sumo seeks to intimidate the other and gain a psychological advantage. This can be represented with a Contested Roll of Intimidation / Willpower, with a wrestler who wins the roll by 5 or more gaining a +1k0 bonus to the subsequent Jiujutsu roll");
 
 	robot.registerGuide( "grappling", "`Grappling` a unique combat situation that may occur during a skirmish\nA samurai initiates a grapple with a Jiujutsu / Agility roll versus Armor TN. If successful, target is grappled until his turn, when he can attempt to control the grapple. Gaining control is a contested Jiujutsu / Strength roll. Winner has control until the other’s turn.\nController may do the following\n`Hit:` Deal unarmed (Strength k1) damage as a Complex action. \n`Throw:` Target is thrown and becomes prone within 5 feet. Target is no longer in the grapple. Complex action.\n`Break:` Ends the grapple as a Simple action. \n`Pass:` As a Free Action, the character may do nothing, choosing to maintain the grapple and retain control");
  
   	robot.registerGuide( "new user", "`New User`, Hello and welcome to Rokugan here are some resources to help you get started.\n[New Player Guide](https://docs.google.com/document/d/1OFCqO9miT47h1jqs41bhxl7zsQRNp7-saMyBPNiKSKA/edit?usp=sharing)\n[Cheat Sheet](https://drive.google.com/file/d/1kcRNXCa_Y0hiT0tzUh2eAIHnnioLnInV/view?usp=sharing)\n[Guide to Factions](https://docs.google.com/document/d/1RzpO_KdyGuPOQxVjAZwTCM24qzDz5uWaS57qzIrJHrU/edit#heading=h.62kyerl65d99)\n[Guide to Monks](https://docs.google.com/document/d/1NiIsR5kdNBE6QSRe_Ga5u-7glbNr_X8vSz3hfctrsdM/edit?usp=sharing)");
	
	//robot.registerGuide( "", "");

}